In [1]:
import numpy as np

In [2]:
emA = np.empty((3, 4), dtype=int)
print("Empty Array")
print(emA)

Empty Array
[[4128860 6029375 3801155 5570652]
 [6619251 7536754 6357084 6815842]
 [7536745 4259932 7340144 6357060]]


In [3]:
arr2=np.array([[1,2,3],[2,3,4],[4,5,6],[7,8,9]])
print("2D array:\n",arr2)

arr3=np.full([3,3],8,dtype = int)
print("Full Array:\n")
print(arr3)

2D array:
 [[1 2 3]
 [2 3 4]
 [4 5 6]
 [7 8 9]]
Full Array:

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [4]:
emz = np.empty((3, 4), dtype=int)
print("Empty Array")
print(emz)

Empty Array
[[4128860 6029375 3801155 5570652]
 [6619251 7536754 6357084 6815842]
 [7536745 4259932 7340144 6357060]]


In [5]:
arrone = np.full([3,3],1,dtype=int)
print(arrone)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
msk = np.array([[2,3,-1],[2,-3,5],[-3,4,8]])
mask = msk>0
print(mask)

[[ True  True False]
 [ True False  True]
 [False  True  True]]


In [7]:
#Check whether a Numpy array contains a specified row
print([2,-3,5] in msk.tolist())
print([2,1,-4] in msk.tolist())

True
False


In [8]:
#How to Remove rows in Numpy array that contains non-numeric values?
arrd = np.array([[2,3,-1],[2,-3,5],[-3,4,8],[2,np.nan,np.nan]])
print(arrd[~np.isnan(arrd).any(axis=1)])

[[ 2.  3. -1.]
 [ 2. -3.  5.]
 [-3.  4.  8.]]


In [9]:
#Remove single-dimensional entries from the shape of an array
x = np.zeros((3, 1, 4))
print(np.squeeze(x).shape)

(3, 4)


In [10]:
#Find the number of occurrences of a sequence in a NumPy array
arrd = np.array([[2,3,-1],[2,-3,5],[-3,4,8],[2,np.nan,np.nan]])
count = repr(arrd).count("3")
print(count)

3


In [11]:
#Masking
arr11=np.array([1,2,3,4,5,6,7,8,9,9])
mask=np.array([0,1,1,0,1,0,1,0,0])
b=arr11[mask]
print(b)
count = repr(mask).count("0")
print(count)

[1 2 2 1 2 1 2 1 1]
5


In [12]:
#Find the most frequent value in a NumPy array
arrc =np.array([0,1,1,0,1,0,1,0,0])
x= np.bincount(arrc).argmax()
print(x)

0


In [13]:
#Combining a one and a two-dimensional NumPy Array
arr1d = np.arange(1,7)
print(arr1d)
arr2d = np.arange(3,15).reshape(2,6)
print(arr2d)
for a,b in np.nditer([arr1d,arr2d]):
    print("%d:%d" % (a,b) , )

[1 2 3 4 5 6]
[[ 3  4  5  6  7  8]
 [ 9 10 11 12 13 14]]
1:3
2:4
3:5
4:6
5:7
6:8
1:9
2:10
3:11
4:12
5:13
6:14


In [14]:
# How to build an array of all combinations of two NumPy arrays?
arx = np.array([[2,3,-1],[2,-3,5],[-3,4,8]])
ary = np.array([[1,2,4],[3,-2,5],[4,-5,9]])
comb_arr = np.array(np.meshgrid(arx,ary)).T.reshape(-1,3)
print(comb_arr)

[[ 2  1  2]
 [ 2  2  4]
 [ 2  3  2]
 [-2  2  5]
 [ 2  4  2]
 [-5  2  9]
 [ 3  1  3]
 [ 2  3  4]
 [ 3  3  3]
 [-2  3  5]
 [ 3  4  3]
 [-5  3  9]
 [-1  1 -1]
 [ 2 -1  4]
 [-1  3 -1]
 [-2 -1  5]
 [-1  4 -1]
 [-5 -1  9]
 [ 2  1  2]
 [ 2  2  4]
 [ 2  3  2]
 [-2  2  5]
 [ 2  4  2]
 [-5  2  9]
 [-3  1 -3]
 [ 2 -3  4]
 [-3  3 -3]
 [-2 -3  5]
 [-3  4 -3]
 [-5 -3  9]
 [ 5  1  5]
 [ 2  5  4]
 [ 5  3  5]
 [-2  5  5]
 [ 5  4  5]
 [-5  5  9]
 [-3  1 -3]
 [ 2 -3  4]
 [-3  3 -3]
 [-2 -3  5]
 [-3  4 -3]
 [-5 -3  9]
 [ 4  1  4]
 [ 2  4  4]
 [ 4  3  4]
 [-2  4  5]
 [ 4  4  4]
 [-5  4  9]
 [ 8  1  8]
 [ 2  8  4]
 [ 8  3  8]
 [-2  8  5]
 [ 8  4  8]
 [-5  8  9]]
