# Lab1

# Dhruv Karmokar 21BAI1604

##### Importing Required Libraries:

In [2]:
import numpy as np

### 1.	How to create an empty and a full NumPy array?

In [4]:
# Create an empty array
empa = np.empty((3, 4), dtype=int)
print("Empty Array")
print(empa)
  
# Create a full array
flla = np.full([3, 3], 64, dtype=int)
print("\n Full Array")
print(flla)

Empty Array
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

 Full Array
[[64 64 64]
 [64 64 64]
 [64 64 64]]


### 2.	Create a Numpy array filled with all zeros

In [5]:
#The code creates a NumPy array of length 5 filled with zeros and of integer type, and then prints the array to the console.
zeros_arr = np.zeros(5,int)
print(zeros_arr)

[0 0 0 0 0]


### 3.	Create a Numpy array filled with all ones

In [6]:
#The code creates a NumPy array of length 6 filled with ones and of integer type, and then prints the array to the console.
ones_arr = np.ones(6,int)
print(ones_arr)

[1 1 1 1 1 1]


### 4.	Check whether a Numpy array contains a specified row

In [7]:
#Code checks if a given row exists in 2D NumPy array using Boolean indexing.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_to_find = [4, 5, 6]

if np.any(np.all(arr == row_to_find, axis=1)):
    print("The row is present in the array")
else:
    print("The row is not present in the array")

The row is present in the array


### 5.	How to Remove rows in Numpy array that contains non-numeric values?

In [8]:
#Remove rows containing NaN values from 2D NumPy array arr.
arr = np.array([[1, 2, 3],
                [4, np.nan, 6],
                [7, 8, 9],
                [10, np.nan, np.nan]])

nan_rows = np.isnan(arr).any(axis=1)
clean_arr = arr[~nan_rows]
print(clean_arr)

[[1. 2. 3.]
 [7. 8. 9.]]


### 6.	Remove single-dimensional entries from the shape of an array

In [9]:
#Code removes length-1 dimensions from a 3D NumPy array using np.squeeze().
arr = np.array([[[1, 2, 3]],
                [[4, 5, 6]]])

print("Original shape:", arr.shape)
squeezed_arr = np.squeeze(arr)
print("Squeezed shape:", squeezed_arr.shape)

Original shape: (2, 1, 3)
Squeezed shape: (2, 3)


### 7.	Find the number of occurrences of a sequence in a NumPy array

In [10]:
#Count the number of occurrences of a given sequence in a NumPy array.
arr = np.array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3])
seq = "1, 2, 3"
output = repr(arr).count(str(seq))
print(output)

3


### 8.	Find the most frequent value in a NumPy array

In [11]:
#Find the most frequent value in a NumPy array.
arr = np.array([1, 2, 3, 4, 5, 1, 2, 3, 1, 1])
counts = np.bincount(arr.astype('int64'))
most_frequent_value = np.argmax(counts)
print("Most frequent value:", most_frequent_value)

Most frequent value: 1


### 9.	Combining a one and a two-dimensional NumPy Array

In [12]:
#Code stacks two NumPy arrays vertically after reshaping the first one.
arr12 = np.array([10, 20, 30])
arr13 = np.array([[40, 50, 60], [70, 80, 90]])

combined_arr = np.concatenate((arr12.reshape(1, -1), arr13), axis=0)

print(combined_arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


### 10.	How to build an array of all combinations of two NumPy arrays?

In [13]:
#Create a new 2D NumPy array from all possible combinations of elements from two input arrays.
array_1 = np.array([1, 2])
array_2 = np.array([4, 6])
print("Array-1")
print(array_1)
print("\nArray-2")
print(array_2)
comb_array = np.array(np.meshgrid(array_1, array_2)).T.reshape(-1, 2)
print("\nCombine array:")
print(comb_array)

Array-1
[1 2]

Array-2
[4 6]

Combine array:
[[1 4]
 [1 6]
 [2 4]
 [2 6]]
