In [1]:
import numpy as np

In [2]:
coff = np.array([
    [9,11,3,5,7],
    [11,14,4,7,10],
    [3,4,2,3,4],
    [5,7,3,5,7],
    [7,10,4,7,10]
])
consts = np.array([1,1,-1,-1,-1])

In [3]:
sol = np.linalg.solve(coff,consts)

In [4]:
sol

array([ 0.06713781,  0.43286219, -1.19257951, -0.6819788 ,  0.3745583 ])

In [6]:
cof = np.array([
    [6,4,9],
    [4,6,9],
    [9,9,17]
])
cont = np.array([-1,-1,1])



In [8]:
sln = np.linalg.solve(cof,cont)
sln

array([-3.25, -3.25,  3.5 ])

In [11]:
as1 = 0.0671*np.array([2,2,1])
as2 = 0.4329*np.array([3,2,1])
as3 = -1.1926*np.array([1,0,1])
as4 = -0.6820*np.array([2,0,1])
as5 = 0.3746*np.array([3,0,1])
as1


array([0.1342, 0.1342, 0.0671])

In [12]:
as2

array([1.2987, 0.8658, 0.4329])

In [13]:
as3

array([-1.1926, -0.    , -1.1926])

In [14]:
as4

array([-1.364, -0.   , -0.682])

In [15]:
as5

array([1.1238, 0.    , 0.3746])

In [18]:
as1+as2+as3+as4+as5

array([ 1.e-04,  1.e+00, -1.e+00])