***BASIC NUMPY***

In [11]:
print("OM NANAH SHIVAAY")

OM NANAH SHIVAAY


In [14]:
import numpy as np

In [18]:
arr = np.array([3,6,32,7], np.int8)
arr

array([ 3,  6, 32,  7], dtype=int8)

In [22]:
print(arr[0])
print(arr.shape)
print(arr.dtype)

3
(4,)
int8


In [23]:
arr[2]= 47
print(arr)

[ 3  6 47  7]


#Array Creation 

*Conversion from other Python Structures*

In [24]:
listarr = np.array([[1,2,3],[5,8,5],[0,3,1]])
listarr

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [25]:
print(listarr.dtype)
print(listarr.shape)
print(listarr.size)

int32
(3, 3)
9


In [27]:
listarr[2,0]=5
print(listarr)

[[1 2 5]
 [5 8 5]
 [5 3 1]]


*Intrinsic numpy array Creation Objects, 1s,0s*

In [28]:
zrs = np.zeros((2,3))
ons = np.ones((3,2))
print(zrs)
print(ons)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [47]:
rng = np.arange(9)
print(rng.reshape(3,3))
rng

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
lspace = np.linspace(1,5,12)
lspace
#Gives 12 numbers btwn 1 to 5 equally linearly spaced

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [48]:
emp = np.empty((3,4))
emp
emp.ravel()

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [36]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [39]:
ide = np.eye(3)
print(ide)
# ide = np.identity(3)
print(ide.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


In [45]:
arr1 = np.arange(30)
print(arr1)
arr1.reshape(3,10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [49]:
listarr.sum(axis=0)

array([11, 13, 11])

In [50]:
listarr.sum(axis=1)

array([ 8, 18,  9])

In [51]:
listarr.T

array([[1, 5, 5],
       [2, 8, 3],
       [5, 5, 1]])

In [52]:
ar = listarr.T
ar

array([[1, 5, 5],
       [2, 8, 3],
       [5, 5, 1]])

In [53]:
ar.flat

In [54]:
for i in ar.flat:
    print(i)

1
5
5
2
8
3
5
5
1


In [55]:
ar.ndim
#No. of dimension

2

In [56]:
ar.size

9

In [57]:
ar.nbytes

36

In [58]:
one = np.array([1,3,4,63,2])

In [61]:
print(one.argmax())
#index of Max element
print(one.argmin())

3
0


In [63]:
one.argsort()

array([0, 1, 4, 2, 3], dtype=int64)

In [64]:
ar

array([[1, 5, 5],
       [2, 8, 3],
       [5, 5, 1]])

In [65]:
ar.argsort()

array([[0, 1, 2],
       [0, 2, 1],
       [2, 0, 1]], dtype=int64)

In [66]:
ar.argmin()

0

In [67]:
ar.argmax()

4

In [68]:
ar.argmax(axis=0)

array([2, 1, 0], dtype=int64)

In [69]:
print(ar.argmax(axis=1))

[1 1 0]


In [70]:
ar.ravel()

array([1, 5, 5, 2, 8, 3, 5, 5, 1])

In [72]:
ar.reshape((9,1))

array([[1],
       [5],
       [5],
       [2],
       [8],
       [3],
       [5],
       [5],
       [1]])

In [73]:
ar2 = np.array([[1, 8, 9],
       [1, 7, 3],
       [5, 4, 1]])

In [74]:
ar+ar2

array([[ 2, 13, 14],
       [ 3, 15,  6],
       [10,  9,  2]])

In [75]:
ar*ar2

array([[ 1, 40, 45],
       [ 2, 56,  9],
       [25, 20,  1]])

In [76]:
np.sqrt(ar)

array([[1.        , 2.23606798, 2.23606798],
       [1.41421356, 2.82842712, 1.73205081],
       [2.23606798, 2.23606798, 1.        ]])

In [77]:
ar.sum()

35

In [79]:
np.where(ar>3)

(array([0, 0, 1, 2, 2], dtype=int64), array([1, 2, 1, 0, 1], dtype=int64))

In [80]:
np.count_nonzero(ar)

9

In [81]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [82]:
import sys

In [83]:
par = [0,4,55,2]

In [84]:
npar = np.array(par)

In [85]:
sys.getsizeof(1)*len(par)

112

In [86]:
npar.itemsize * npar.size

16