In [1]:
#importing numpy
import numpy as np

In [2]:
#1D array
arr1=np.array([1,2,3,4,5,6])
print("1D array:",arr1)

1D array: [1 2 3 4 5 6]


In [3]:
#2D array
arr2=np.array([[1,2,3],[2,3,4],[4,5,6],[7,8,9]])
print("2D array:",arr2)

2D array: [[1 2 3]
 [2 3 4]
 [4 5 6]
 [7 8 9]]


In [16]:
#understand attributes
print("Type:",type(arr2))
print("Datatype:",arr1.dtype)
print("Shape:",arr1.shape)
print("Size:",arr1.size)
print("Item size:", arr1.itemsize)
print("No. of Dimensions:", arr1.ndim)
print("No. of Dimensions:", arr2.ndim)
print("No. of bytes:", arr1.nbytes)

Type: <class 'numpy.ndarray'>
Datatype: int32
Shape: (6,)
Size: 6
Item size: 4
No. of Dimensions: 1
No. of Dimensions: 2
No. of bytes: 24


In [17]:
#Creating Special Arrays
#Zeros
arr3=np.zeros((5,2),dtype=int)
print("arr3 with zeroes:\n",arr3)
arr4=np.ones((3,4),dtype=float)
print("arr4 with ones\n",arr4)
arr5=np.eye(4,4)
print("arr5 Identity matrix:\n",arr5)
arr6=np.random.rand(3,2)
print("arr6 Random array:\n",arr6)
arr7=np.random.randint(7,size=(2,6))
print("arr7 Random Integer Array:\n",arr7)


arr3 with zeroes:
 [[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
arr4 with ones
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
arr5 Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
arr6 Random array:
 [[0.86139387 0.79237365]
 [0.11664318 0.4494292 ]
 [0.36555244 0.77991803]]
arr7 Random Integer Array:
 [[4 6 3 6 4 5]
 [6 1 4 1 1 5]]


In [6]:
#Creating Arrays with "arange"
arr8=np.arange(1,10,2)
print('Array created with arange:',arr8)

Array created with arange: [1 3 5 7 9]


In [7]:
#Creating Arrays with "linspace"
arr9=np.linspace(1,10,50)
print('Array created with linspace requesting 50 elements within 1 to 10:\n',arr9)

Array created with linspace requesting 50 elements within 1 to 10:
 [ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [8]:
#Slicing
arr10=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(arr10)
print("Row2:",arr10[1,:])
print("Column2:",arr10[:,1])
print("Elements 7,8,12,13:\n",arr10[1:3,1:3])
print("All Elements:\n",arr10[:,:])
#Strides
print("Strides:\n",arr10[0::2,1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row2: [ 6  7  8  9 10]
Column2: [ 2  7 12 17]
Elements 7,8,12,13:
 [[ 7  8]
 [12 13]]
All Elements:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Strides:
 [[ 2  3]
 [12 13]]


In [9]:
#Masking
arr11=np.array([1,2,3,4,5,6,7,8,9,9])
mask=np.array([0,1,1,0,1,0,1,0,0])
b=arr11[mask]
print(b)

[1 2 2 1 2 1 2 1 1]


In [10]:
arr12=np.array([[1,2,3,4,5],[6,7,8,9,9]])
print(arr12)
print("Sum:\t",np.sum(arr12))
print("Sum:\t", np.sum(arr12,axis=0))
print("Product: \t",np.prod(arr12))
print("Product: \t",np.prod(arr12,axis=0))
print("Minimum:\t",np.min(arr12,axis=0))
print("Maximum:\t",np.max(arr12,axis=0))
print("Mean:\t",np.mean(arr12,axis=0))
print("Variance:\t",np.var(arr12,axis=0))
print("Standard Deviation:\t",np.std(arr12,axis=0))
print("Average:\t",np.average(arr12,axis=0))
print("Weighted Average:\t",np.average(arr12,weights=[1,2,3,4,5],axis=1))

[[1 2 3 4 5]
 [6 7 8 9 9]]
Sum:	 54
Sum:	 [ 7  9 11 13 14]
Product: 	 3265920
Product: 	 [ 6 14 24 36 45]
Minimum:	 [1 2 3 4 5]
Maximum:	 [6 7 8 9 9]
Mean:	 [3.5 4.5 5.5 6.5 7. ]
Variance:	 [6.25 6.25 6.25 6.25 4.  ]
Standard Deviation:	 [2.5 2.5 2.5 2.5 2. ]
Average:	 [3.5 4.5 5.5 6.5 7. ]
Weighted Average:	 [3.66666667 8.33333333]


In [11]:
#Scalar Operations
arr13=np.array([1,2,3])
arr14=np.array([4,5,6])
arr15=arr13+arr14
arr16=arr13-arr14
print("Summation:\t",arr15)
print("Difference:\t",arr16)
arr16+=5
print("Previous output after adding 5:",arr16)

##Try out leftout scalar operations

Summation:	 [5 7 9]
Difference:	 [-3 -3 -3]
Previous output after adding 5: [2 2 2]


In [12]:
#Relational operations
result1=arr15==arr16
print(result1)

[False False False]


In [13]:
#Try Out other relational operators


In [14]:
#Trigonometric and Logarithmic operations
arr17=np.array([15,30,45,90])
result7=np.sin(arr17)
print("Sin values:\t",result7)
result8=np.log(arr17)
print("Log values:\t",result8)
#Try other trignomatric functions

Sin values:	 [ 0.65028784 -0.98803162  0.85090352  0.89399666]
Log values:	 [2.7080502  3.40119738 3.80666249 4.49980967]


In [15]:
#Vector operations
#Try them on your own : Inner product, Outer Product, Dot Product